# Question

Is this function safe? Why or why not?

```js
const getUser = async (userId) => {
  const url = `https://jsonplaceholder.typicode.com/users/${userId}`;
  const response = await fetch(url);
  const users = await response.json();
  console.log(users);
  return users;
};
getUser(-1);
```

Again, running the code gives you the answer, so try to figure it out on your own first!

# Answer

I believe that this function is not safe. That is because it does not have any way of handling any errors. It does not include a `try/catch` or any guard clauses.

This particular invocation of the function will look for a user that has an `userId` of -1 which is probably likely to cause an error since `userId`s are not usually negative numbers.

This is how I would implement `try/catch` and guard clauses to try to make this function safer:

```js
const getUser = async (userId) => {
  try {
    const url = `https://jsonplaceholder.typicode.com/users/${userId}`;

    const response = await fetch(url);

    if (!response.ok)
      throw new Error(
        `Fetch failed. ${response.status} ${response.statusText}`
      );

    const contentType = response.headers.get("content-type");
    if (contentType !== null && contentType.includes("application/json")) {
      const users = await response.json();
      console.log(users);
      return [users, null];
    }

    const textData = await response.text();
    return [textData, null];
  } catch (error) {
    console.error(error.message);
    return [null, error];
  }
};
```

# Teacher Feedback
